// Schema type definitions - Transformed types for Element constructors and data structures
// These are NOT DTOs - they are camelCase transformed data ready for use in the app

// Import and re-export SlotDefinition from import_types (it's part of the DTO structure but used everywhere)
import type { SlotDefinition } from '../import_types';
export type { SlotDefinition };

// ============================================================================
// Transformed Types - Used by Element constructors and data structures
// ============================================================================

/**
 * Slot data for SlotElement constructor
 * Transformed from SlotDTO with camelCase
 */
export interface SlotData {
  range?: string;
  description?: string;
  slotUri?: string;  // transformed from slot_uri
  identifier?: boolean;
  required?: boolean;
  multivalued?: boolean;
}

/**
 * Enum data for EnumElement constructor
 * Transformed from EnumDTO
 */
export interface EnumData {
  description?: string;
  permissibleValues?: Record<string, {  // transformed from permissible_values
    description?: string;
    meaning?: string;
  }>;
}

/**
 * Type data for TypeElement constructor
 * Transformed from TypeDTO with camelCase
 */
export interface TypeData {
  uri: string;
  base: string;
  repr?: string;
  description?: string;
  notes?: string;  // Normalized to string (join array if needed)
  exactMappings?: string[];  // transformed from exact_mappings
  closeMappings?: string[];  // transformed from close_mappings
  broadMappings?: string[];  // transformed from broad_mappings
  conformsTo?: string;  // transformed from conforms_to
}

/**
 * Class data for ClassElement constructor
 * From bdchm.processed.json (generated by transform_schema.py)
 * All slots, slot_usage, and attributes are merged into attributes field
 */
export interface ClassData {
  name: string;
  description: string;
  parent?: string;  // Normalized from is_a
  abstract: boolean;
  attributes: Record<string, SlotDefinition>;  // Pre-computed with slotId and inherited_from
  class_url?: string;  // Expanded from class_uri using prefixes
}

/**
 * Variable specification data for VariableElement constructor (transformed)
 */
export interface VariableSpec {
  maps_to: string;  // Class ID that this variable maps to (no transformation needed - same as DTO)
  variableLabel: string;
  dataType: string;
  ucumUnit: string;
  curie: string;
  variableDescription: string;
}

/**
 * Complete transformed schema data ready for Element constructors
 */
export interface SchemaData {
  classes: ClassData[];
  enums: Map<string, EnumData>;
  slots: Map<string, SlotData>;
  types: Map<string, TypeData>;  // LinkML types from types.yaml
  variables: VariableSpec[];
}

/**
 * Enum value (used in processing enum metadata)
 */
export interface EnumValue {
  key: string;
  description?: string;
}

/**
 * Field mapping specification for transforming DTOs to Data types.
 * Maps DTO field names (keys) to Data field names (values).
 * If value is undefined, the field is copied as-is.
 */
export interface FieldMapping {
  [dtoField: string]: string | undefined;
}
